<a href="https://colab.research.google.com/github/Aniketchhet/Gaussian_elimination/blob/main/Copy_of_GaussianElimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Gaussian Elimination


In [ ]:
## importing requirement library
import numpy as np


In [ ]:
##Auxiliary functions
def swap_rows(M,ind1,ind2):
  M=M.copy()
  M[[ind1,ind2]]=M[[ind2,ind1]]
  return M


In [ ]:
a=np.array([[2,3,7],[6,8,1],[7,1,2]])
a_swapped=swap_rows(a,0,2)
print(a)
print(a_swapped)

[[2 3 7]
 [6 8 1]
 [7 1 2]]
[[7 1 2]
 [6 8 1]
 [2 3 7]]


In [ ]:
def get_first_non_zero_val_col(M,col,starting_row):
  col_arr=M[starting_row:,col]
  for i,val in enumerate(col_arr):
    if not np.isclose(val,0,atol=1e-5):
      ind=i+starting_row
      return ind
  return -1

In [ ]:
a=np.array([[6,4,8,1],[0,8,6,4],[0,0,0,3],[0,0,5,9]])
print(get_first_non_zero_val_col(a,2,2))

3


In [ ]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(get_first_non_zero_val_col(N,-1,2))

3


In [ ]:
def get_ind_nonzero_row(M,row,aug=False):
  M=M.copy()
  if aug==True:
    M=M[:,:-1]
  row_arr=M[row]
  for i,val in enumerate(row_arr):
    if not np.isclose(val,0,atol=1e-5):
      return i
  return -1

In [ ]:
print(get_ind_nonzero_row(a,1))

1


In [ ]:
def augmented_mat(A,B):
  aug_m=np.hstack((A,B))
  return aug_m

In [ ]:
A=np.array([[2,-1,1],[2,2,4],[4,1,0]])
B=np.array([[1],[-2],[-1]])
print(augmented_mat(A,B))

[[ 2 -1  1  1]
 [ 2  2  4 -2]
 [ 4  1  0 -1]]


In [ ]:
def row_echelon_form(A,B):
  #check for singularity
  det_a=np.linalg.det(A);
  if np.isclose(det_a,0,atol=1e-5):
    print("Its a singular function, try again!!")
    return
  #creating the copy so that it does not update or distort the original
  A=A.copy()
  B=B.copy()
  A=A.astype('float64')
  B=B.astype('float64')
  num_rows=len(A)
  M=augmented_mat(A,B)
  for row in range(num_rows):
    pivot_candidate=M[row,row]
    if np.isclose(pivot_candidate,0,atol=1e-5):
      i=get_first_non_zero_val_col(M,row,row)
      swap_rows(M,i,row)
      pivot=M[row,row]
    else:
      pivot=pivot_candidate
    ## row scaling to make the pivot equal to 1
    M[row]=(1/pivot)*M[row]
    for j in range(row+1,num_rows):
      val=M[j,row]
      M[j]=M[j]-val*M[row]
  return M



In [ ]:
A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
row_echelon_form(A,B)

array([[1. , 2. , 3. , 1. ],
       [0. , 1. , 0. , 2. ],
       [0. , 0. , 1. , 0.8]])

In [ ]:
def back_substitution(M):
  M=M.copy()
  num_rows=M.shape[0]
  for row in reversed(range(num_rows)):
    substituition_row=M[row]
    ind=get_ind_nonzero_row(M,row,aug=True)

    for j in range(row):
      row_to_reduce=M[j].copy()
      val=row_to_reduce[ind]
      row_to_reduce=row_to_reduce-val*substituition_row
      M[j,:]=row_to_reduce
  solution=M[:,-1]
  return solution


In [ ]:
def gaussianelimination(A,B):
  row_elch_form_M=row_echelon_form(A,B)
  solution=back_substitution(row_elch_form_M)
  return solution

In [ ]:
A=np.array([[1,2,3],[2,6,12],[4,-8,4]])
B=np.array([[10],[4],[8]])
lst=gaussianelimination(A,B)
print(lst)


[14.  4. -4.]
